name: '[CI] Analyze'
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello, world!"
      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: 3.24.1
          channel: stable
      
      - name: check format
        run: dart format -o none --set-exit-if-changed $(find lib/ test/ -name "*.dart" -not \( -name "*.*freezed.dart" -o -name "*.*g.dart" -o -name "*.*gr.dart" -o -name "*.*gen.dart" -o -name "*.*mocks.dart" \) )

      - name: analyze
        run: flutter analyze
        
      - name: test
        run: flutter test
       
        